spring.application.name=project
# Database Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/your_database_name
spring.datasource.username=your_username
spring.datasource.password=your_password

# Driver Class Name (Optional for newer Spring Boot versions as it's often auto-detected)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
